# Generated by Django 3.1.2 on 2022-05-07 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist_title',
            new_name='album_title',
        ),
    ]
