# Generated by Django 3.1.2 on 2022-09-06 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0002_todolist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='check',
        ),
    ]
