# Generated by Django 4.1.4 on 2023-07-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_alter_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('founder', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='OndoDoctors',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('birth_day', models.CharField(max_length=300)),
                ('specialty', models.CharField(max_length=300)),
                ('local_govt', models.CharField(max_length=200)),
                ('medical_school', models.CharField(max_length=200)),
                ('hospital_worked', models.CharField(max_length=200)),
                ('positions', models.CharField(max_length=300)),
                ('awards', models.CharField(max_length=200)),
            ],
        ),
    ]
