# Generated by Django 5.0.6 on 2024-05-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('sensor_id', models.CharField(max_length=50)),
                ('sensor_type', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('battery_level', models.IntegerField()),
                ('calibration_date', models.DateTimeField()),
                ('environment_context', models.JSONField()),
                ('data_quality', models.CharField(max_length=20)),
            ],
        ),
    ]
