# Generated by Django 3.1.2 on 2022-05-30 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_members'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Adeolas',
        ),
    ]
