# Generated by Django 3.1.2 on 2022-06-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20220530_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='jss1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullnames', models.CharField(max_length=200)),
                ('first_test', models.IntegerField(default=0)),
                ('second_test', models.IntegerField(default=0)),
                ('third_test', models.IntegerField(default=0)),
                ('total_tests', models.IntegerField(default=0)),
                ('exams', models.IntegerField(default=0)),
                ('final_scores', models.IntegerField(default=0)),
                ('grades', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='jss2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullnames', models.CharField(max_length=200)),
                ('first_test', models.IntegerField(default=0)),
                ('second_test', models.IntegerField(default=0)),
                ('third_test', models.IntegerField(default=0)),
                ('total_tests', models.IntegerField(default=0)),
                ('exams', models.IntegerField(default=0)),
                ('final_scores', models.IntegerField(default=0)),
                ('grades', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='jss3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullnames', models.CharField(max_length=200)),
                ('first_test', models.IntegerField(default=0)),
                ('second_test', models.IntegerField(default=0)),
                ('third_test', models.IntegerField(default=0)),
                ('total_tests', models.IntegerField(default=0)),
                ('exams', models.IntegerField(default=0)),
                ('final_scores', models.IntegerField(default=0)),
                ('grades', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='sss1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullnames', models.CharField(max_length=200)),
                ('first_test', models.IntegerField(default=0)),
                ('second_test', models.IntegerField(default=0)),
                ('third_test', models.IntegerField(default=0)),
                ('total_tests', models.IntegerField(default=0)),
                ('exams', models.IntegerField(default=0)),
                ('final_scores', models.IntegerField(default=0)),
                ('grades', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='sss2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullnames', models.CharField(max_length=200)),
                ('first_test', models.IntegerField(default=0)),
                ('second_test', models.IntegerField(default=0)),
                ('third_test', models.IntegerField(default=0)),
                ('total_tests', models.IntegerField(default=0)),
                ('exams', models.IntegerField(default=0)),
                ('final_scores', models.IntegerField(default=0)),
                ('grades', models.CharField(max_length=1)),
            ],
        ),
    ]
